[project]
name = "agenticai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "vikasjha2003", email = "vikas2003jha@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.4.2",
    "langchain-google-genai>=4.4.0",
    "langchain-groq>=1.1.3",
    "langgraph>=1.2.11",
    "python-dotenv>=1.2.3",
]

[project.scripts]
agenticai = "agenticai:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
